---
name: checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  checks:
    name: Running checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checking out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --frozen

      - name: Check code
        run: uv run ruff check .

      - name: Check code format
        run: uv run ruff format --check .

      - name: Type check using mypy
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest
